[project]
name = "shared-clipboard"
version = "0.1.0"
description = "Truly cross-platform clipboard sharing"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "requests>=2.32.4",
    "zeroconf>=0.147.0",
]
